// <auto-generated />
namespace Day3_3.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class namelength : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(namelength));
        
        string IMigrationMetadata.Id
        {
            get { return "201803100948046_namelength"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
